package apdu

// Code generated by "go run github.com/zemnmez/cardauth/apdu/gen/instrs instrs.go" DO NOT EDIT.

//go:generate go run github.com/zemnmez/cardauth/apdu/gen/instrs $GOFILE
//go:generate gofmt -w -s $GOFILE
//go:generate go run golang.org/x/tools/cmd/stringer -type=Instruction
//go:generate go run golang.org/x/tools/cmd/stringer -type=Instruction -output=instruction_infostring.go -linecomment
//go:generate go run github.com/zemnmez/cardauth/apdu/gen/repl -from=_Instruction -to=_Info_Instruction -file=instruction_infostring.go
//go:generate gofmt -w -r String->Info ./instruction_infostring.go

// Instruction represents a smart card instruction as defined in ISO/IEC 7816-4:2005(E)
type Instruction byte

const (
	InstrDeactivateFile                 Instruction = 0x04 // 'DEACTIVATE FILE' instruction as defined in ISO/IEC 7816-4:2005(E) Part 9
	InstrEraseRecord                    Instruction = 0x0C // 'ERASE RECORD (S)' instruction as defined in ISO/IEC 7816-4:2005(E) 7.3.8
	InstrEraseBinary                    Instruction = 0x0E // 'ERASE BINARY' instruction as defined in ISO/IEC 7816-4:2005(E) 7.2.7
	InstrEraseBinaryAlt                 Instruction = 0x0F // 'ERASE BINARY' instruction as defined in ISO/IEC 7816-4:2005(E) 7.2.7
	InstrPerformScqlOperation           Instruction = 0x10 // 'PERFORM SCQL OPERATION' instruction as defined in ISO/IEC 7816-4:2005(E) Part 7
	InstrPerformTransactionOperation    Instruction = 0x12 // 'PERFORM TRANSACTION OPERATION' instruction as defined in ISO/IEC 7816-4:2005(E) Part 7
	InstrPerformUserOperation           Instruction = 0x14 // 'PERFORM USER OPERATION' instruction as defined in ISO/IEC 7816-4:2005(E) Part 7
	InstrVerify                         Instruction = 0x20 // 'VERIFY' instruction as defined in ISO/IEC 7816-4:2005(E) 7.5.6
	InstrVerifyAlt                      Instruction = 0x21 // 'VERIFY' instruction as defined in ISO/IEC 7816-4:2005(E) 7.5.6
	InstrManageSecurityEnvironment      Instruction = 0x22 // 'MANAGE SECURITY ENVIRONMENT' instruction as defined in ISO/IEC 7816-4:2005(E) 7.5.11
	InstrChangeReferenceData            Instruction = 0x24 // 'CHANGE REFERENCE DATA' instruction as defined in ISO/IEC 7816-4:2005(E) 7.5.7
	InstrDisableVerificationRequirement Instruction = 0x26 // 'DISABLE VERIFICATION REQUIREMENT' instruction as defined in ISO/IEC 7816-4:2005(E) 7.5.9
	InstrEnableVerificationRequirement  Instruction = 0x28 // 'ENABLE VERIFICATION REQUIREMENT' instruction as defined in ISO/IEC 7816-4:2005(E) 7.5.8
	InstrPerformSecurityOperation       Instruction = 0x2A // 'PERFORM SECURITY OPERATION' instruction as defined in ISO/IEC 7816-4:2005(E) Part 8
	InstrResetRetryCounter              Instruction = 0x2C // 'RESET RETRY COUNTER' instruction as defined in ISO/IEC 7816-4:2005(E) 7.5.10
	InstrActivateFile                   Instruction = 0x44 // 'ACTIVATE FILE' instruction as defined in ISO/IEC 7816-4:2005(E) Part 9
	InstrGenerateAsymmetricKeyPair      Instruction = 0x46 // 'GENERATE ASYMMETRIC KEY PAIR' instruction as defined in ISO/IEC 7816-4:2005(E) Part 8
	InstrManageChannel                  Instruction = 0x70 // 'MANAGE CHANNEL' instruction as defined in ISO/IEC 7816-4:2005(E) 7.1.2
	InstrExternalAuthenticate           Instruction = 0x82 // 'EXTERNAL (/ MUTUAL) AUTHENTICATE' instruction as defined in ISO/IEC 7816-4:2005(E) 7.5.4
	InstrGetChallenge                   Instruction = 0x84 // 'GET CHALLENGE' instruction as defined in ISO/IEC 7816-4:2005(E) 7.5.3
	InstrGeneralAuthenticate            Instruction = 0x86 // 'GENERAL AUTHENTICATE' instruction as defined in ISO/IEC 7816-4:2005(E) 7.5.5
	InstrGeneralAuthenticateAlt         Instruction = 0x87 // 'GENERAL AUTHENTICATE' instruction as defined in ISO/IEC 7816-4:2005(E) 7.5.5
	InstrInternalAuthenticate           Instruction = 0x88 // 'INTERNAL AUTHENTICATE' instruction as defined in ISO/IEC 7816-4:2005(E) 7.5.2
	InstrSearchBinary                   Instruction = 0xA0 // 'SEARCH BINARY' instruction as defined in ISO/IEC 7816-4:2005(E) 7.2.6
	InstrSearchBinaryAlt                Instruction = 0xA1 // 'SEARCH BINARY' instruction as defined in ISO/IEC 7816-4:2005(E) 7.2.6
	InstrSearchRecord                   Instruction = 0xA2 // 'SEARCH RECORD' instruction as defined in ISO/IEC 7816-4:2005(E) 7.3.7
	InstrSelect                         Instruction = 0xA4 // 'SELECT' instruction as defined in ISO/IEC 7816-4:2005(E) 7.1.1
	InstrReadBinary                     Instruction = 0xB0 // 'READ BINARY' instruction as defined in ISO/IEC 7816-4:2005(E) 7.2.3
	InstrReadBinaryAlt                  Instruction = 0xB1 // 'READ BINARY' instruction as defined in ISO/IEC 7816-4:2005(E) 7.2.3
	InstrReadRecord                     Instruction = 0xB2 // 'READ RECORD' instruction as defined in ISO/IEC 7816-4:2005(E) (S) 7.3.3
	InstrReadRecordAlt                  Instruction = 0xB3 // 'READ RECORD' instruction as defined in ISO/IEC 7816-4:2005(E) (S) 7.3.3
	InstrGetResponse                    Instruction = 0xC0 // 'GET RESPONSE' instruction as defined in ISO/IEC 7816-4:2005(E) 7.6.1
	InstrEnvelope                       Instruction = 0xC2 // 'ENVELOPE' instruction as defined in ISO/IEC 7816-4:2005(E) 7.6.2
	InstrEnvelopeAlt                    Instruction = 0xC3 // 'ENVELOPE' instruction as defined in ISO/IEC 7816-4:2005(E) 7.6.2
	InstrGetData                        Instruction = 0xCA // 'GET DATA' instruction as defined in ISO/IEC 7816-4:2005(E) 7.4.2
	InstrGetDataAlt                     Instruction = 0xCB // 'GET DATA' instruction as defined in ISO/IEC 7816-4:2005(E) 7.4.2
	InstrWriteBinary                    Instruction = 0xD0 // 'WRITE BINARY' instruction as defined in ISO/IEC 7816-4:2005(E) 7.2.6
	InstrWriteBinaryAlt                 Instruction = 0xD1 // 'WRITE BINARY' instruction as defined in ISO/IEC 7816-4:2005(E) 7.2.6
	InstrWriteRecord                    Instruction = 0xD2 // 'WRITE RECORD' instruction as defined in ISO/IEC 7816-4:2005(E) 7.3.4
	InstrUpdateBinary                   Instruction = 0xD6 // 'UPDATE BINARY' instruction as defined in ISO/IEC 7816-4:2005(E) 7.2.5
	InstrUpdateBinaryAlt                Instruction = 0xD7 // 'UPDATE BINARY' instruction as defined in ISO/IEC 7816-4:2005(E) 7.2.5
	InstrPutData                        Instruction = 0xDA // 'PUT DATA' instruction as defined in ISO/IEC 7816-4:2005(E) 7.4.3
	InstrPutDataAlt                     Instruction = 0xDB // 'PUT DATA' instruction as defined in ISO/IEC 7816-4:2005(E) 7.4.3
	InstrUpdateRecord                   Instruction = 0xDC // 'UPDATE RECORD' instruction as defined in ISO/IEC 7816-4:2005(E) 7.3.5
	InstrUpdateRecordAlt                Instruction = 0xDD // 'UPDATE RECORD' instruction as defined in ISO/IEC 7816-4:2005(E) 7.3.5
	InstrCreateFile                     Instruction = 0xE0 // 'CREATE FILE' instruction as defined in ISO/IEC 7816-4:2005(E) Part 9
	InstrAppendRecord                   Instruction = 0xE2 // 'APPEND RECORD' instruction as defined in ISO/IEC 7816-4:2005(E) 7.3.6
	InstrDeleteFile                     Instruction = 0xE4 // 'DELETE FILE' instruction as defined in ISO/IEC 7816-4:2005(E) Part 9
	InstrTerminateDf                    Instruction = 0xE6 // 'TERMINATE DF' instruction as defined in ISO/IEC 7816-4:2005(E) Part 9
	InstrTerminateEf                    Instruction = 0xE8 // 'TERMINATE EF' instruction as defined in ISO/IEC 7816-4:2005(E) Part 9
	InstrTerminateCardUsage             Instruction = 0xFE // 'TERMINATE CARD USAGE' instruction as defined in ISO/IEC 7816-4:2005(E) Part 9
)

var resolveAlts = map[Instruction]Instruction{
	InstrEraseBinaryAlt:         InstrEraseBinary,
	InstrVerifyAlt:              InstrVerify,
	InstrGeneralAuthenticateAlt: InstrGeneralAuthenticate,
	InstrSearchBinaryAlt:        InstrSearchBinary,
	InstrReadBinaryAlt:          InstrReadBinary,
	InstrReadRecordAlt:          InstrReadRecord,
	InstrEnvelopeAlt:            InstrEnvelope,
	InstrGetDataAlt:             InstrGetData,
	InstrWriteBinaryAlt:         InstrWriteBinary,
	InstrUpdateBinaryAlt:        InstrUpdateBinary,
	InstrPutDataAlt:             InstrPutData,
	InstrUpdateRecordAlt:        InstrUpdateRecord,
}

// Resolve resolves any possible alt Instruction to its primary Instruction.
func (i Instruction) Resolve() Instruction {
	if v, ok := resolveAlts[i]; ok {
		return v
	}

	return i
}
