// Code generated by "stringer -type=Instruction"; DO NOT EDIT.

package apdu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InstrDeactivateFile-4]
	_ = x[InstrEraseRecord-12]
	_ = x[InstrEraseBinary-14]
	_ = x[InstrEraseBinaryAlt-15]
	_ = x[InstrPerformScqlOperation-16]
	_ = x[InstrPerformTransactionOperation-18]
	_ = x[InstrPerformUserOperation-20]
	_ = x[InstrVerify-32]
	_ = x[InstrVerifyAlt-33]
	_ = x[InstrManageSecurityEnvironment-34]
	_ = x[InstrChangeReferenceData-36]
	_ = x[InstrDisableVerificationRequirement-38]
	_ = x[InstrEnableVerificationRequirement-40]
	_ = x[InstrPerformSecurityOperation-42]
	_ = x[InstrResetRetryCounter-44]
	_ = x[InstrActivateFile-68]
	_ = x[InstrGenerateAsymmetricKeyPair-70]
	_ = x[InstrManageChannel-112]
	_ = x[InstrExternalAuthenticate-130]
	_ = x[InstrGetChallenge-132]
	_ = x[InstrGeneralAuthenticate-134]
	_ = x[InstrGeneralAuthenticateAlt-135]
	_ = x[InstrInternalAuthenticate-136]
	_ = x[InstrSearchBinary-160]
	_ = x[InstrSearchBinaryAlt-161]
	_ = x[InstrSearchRecord-162]
	_ = x[InstrSelect-164]
	_ = x[InstrReadBinary-176]
	_ = x[InstrReadBinaryAlt-177]
	_ = x[InstrReadRecord-178]
	_ = x[InstrReadRecordAlt-179]
	_ = x[InstrGetResponse-192]
	_ = x[InstrEnvelope-194]
	_ = x[InstrEnvelopeAlt-195]
	_ = x[InstrGetData-202]
	_ = x[InstrGetDataAlt-203]
	_ = x[InstrWriteBinary-208]
	_ = x[InstrWriteBinaryAlt-209]
	_ = x[InstrWriteRecord-210]
	_ = x[InstrUpdateBinary-214]
	_ = x[InstrUpdateBinaryAlt-215]
	_ = x[InstrPutData-218]
	_ = x[InstrPutDataAlt-219]
	_ = x[InstrUpdateRecord-220]
	_ = x[InstrUpdateRecordAlt-221]
	_ = x[InstrCreateFile-224]
	_ = x[InstrAppendRecord-226]
	_ = x[InstrDeleteFile-228]
	_ = x[InstrTerminateDf-230]
	_ = x[InstrTerminateEf-232]
	_ = x[InstrTerminateCardUsage-254]
}

const _Instruction_name = "InstrDeactivateFileInstrEraseRecordInstrEraseBinaryInstrEraseBinaryAltInstrPerformScqlOperationInstrPerformTransactionOperationInstrPerformUserOperationInstrVerifyInstrVerifyAltInstrManageSecurityEnvironmentInstrChangeReferenceDataInstrDisableVerificationRequirementInstrEnableVerificationRequirementInstrPerformSecurityOperationInstrResetRetryCounterInstrActivateFileInstrGenerateAsymmetricKeyPairInstrManageChannelInstrExternalAuthenticateInstrGetChallengeInstrGeneralAuthenticateInstrGeneralAuthenticateAltInstrInternalAuthenticateInstrSearchBinaryInstrSearchBinaryAltInstrSearchRecordInstrSelectInstrReadBinaryInstrReadBinaryAltInstrReadRecordInstrReadRecordAltInstrGetResponseInstrEnvelopeInstrEnvelopeAltInstrGetDataInstrGetDataAltInstrWriteBinaryInstrWriteBinaryAltInstrWriteRecordInstrUpdateBinaryInstrUpdateBinaryAltInstrPutDataInstrPutDataAltInstrUpdateRecordInstrUpdateRecordAltInstrCreateFileInstrAppendRecordInstrDeleteFileInstrTerminateDfInstrTerminateEfInstrTerminateCardUsage"

var _Instruction_map = map[Instruction]string{
	4:   _Instruction_name[0:19],
	12:  _Instruction_name[19:35],
	14:  _Instruction_name[35:51],
	15:  _Instruction_name[51:70],
	16:  _Instruction_name[70:95],
	18:  _Instruction_name[95:127],
	20:  _Instruction_name[127:152],
	32:  _Instruction_name[152:163],
	33:  _Instruction_name[163:177],
	34:  _Instruction_name[177:207],
	36:  _Instruction_name[207:231],
	38:  _Instruction_name[231:266],
	40:  _Instruction_name[266:300],
	42:  _Instruction_name[300:329],
	44:  _Instruction_name[329:351],
	68:  _Instruction_name[351:368],
	70:  _Instruction_name[368:398],
	112: _Instruction_name[398:416],
	130: _Instruction_name[416:441],
	132: _Instruction_name[441:458],
	134: _Instruction_name[458:482],
	135: _Instruction_name[482:509],
	136: _Instruction_name[509:534],
	160: _Instruction_name[534:551],
	161: _Instruction_name[551:571],
	162: _Instruction_name[571:588],
	164: _Instruction_name[588:599],
	176: _Instruction_name[599:614],
	177: _Instruction_name[614:632],
	178: _Instruction_name[632:647],
	179: _Instruction_name[647:665],
	192: _Instruction_name[665:681],
	194: _Instruction_name[681:694],
	195: _Instruction_name[694:710],
	202: _Instruction_name[710:722],
	203: _Instruction_name[722:737],
	208: _Instruction_name[737:753],
	209: _Instruction_name[753:772],
	210: _Instruction_name[772:788],
	214: _Instruction_name[788:805],
	215: _Instruction_name[805:825],
	218: _Instruction_name[825:837],
	219: _Instruction_name[837:852],
	220: _Instruction_name[852:869],
	221: _Instruction_name[869:889],
	224: _Instruction_name[889:904],
	226: _Instruction_name[904:921],
	228: _Instruction_name[921:936],
	230: _Instruction_name[936:952],
	232: _Instruction_name[952:968],
	254: _Instruction_name[968:991],
}

func (i Instruction) String() string {
	if str, ok := _Instruction_map[i]; ok {
		return str
	}
	return "Instruction(" + strconv.FormatInt(int64(i), 10) + ")"
}
