// Code generated by "stringer -type=Status"; DO NOT EDIT.

package apdu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusNoFurtherQualification-36864]
	_ = x[StatusBytesAvailable-25087]
	_ = x[StatusWarningNonVolatileMemoryUnchanged-25343]
	_ = x[StatusWarningNonVolatileMemoryChanged-25599]
	_ = x[StatusErrorNonVolatileMemoryUnchanged-25855]
	_ = x[StatusErrorNonVolatileMemoryChanged-26111]
	_ = x[StatusErrorSecurityIssue-26367]
	_ = x[StatusErrorWrongLength-26368]
	_ = x[StatusErrorFunctionUnsupported-26879]
	_ = x[StatusErrorCommandNotAllowed-27135]
	_ = x[StatusErrorWrongParametersWithInfo-27391]
	_ = x[StatusErrorWrongParameters-27392]
	_ = x[StatusErrorWrongLe-27903]
	_ = x[StatusErrorUnsupportedInstructionCode-27904]
	_ = x[StatusErrorUnsupportedClass-28160]
	_ = x[StatusErrorUnknown-28416]
}

const _Status_name = "StatusBytesAvailableStatusWarningNonVolatileMemoryUnchangedStatusWarningNonVolatileMemoryChangedStatusErrorNonVolatileMemoryUnchangedStatusErrorNonVolatileMemoryChangedStatusErrorSecurityIssueStatusErrorWrongLengthStatusErrorFunctionUnsupportedStatusErrorCommandNotAllowedStatusErrorWrongParametersWithInfoStatusErrorWrongParametersStatusErrorWrongLeStatusErrorUnsupportedInstructionCodeStatusErrorUnsupportedClassStatusErrorUnknownStatusNoFurtherQualification"

var _Status_map = map[Status]string{
	25087: _Status_name[0:20],
	25343: _Status_name[20:59],
	25599: _Status_name[59:96],
	25855: _Status_name[96:133],
	26111: _Status_name[133:168],
	26367: _Status_name[168:192],
	26368: _Status_name[192:214],
	26879: _Status_name[214:244],
	27135: _Status_name[244:272],
	27391: _Status_name[272:306],
	27392: _Status_name[306:332],
	27903: _Status_name[332:350],
	27904: _Status_name[350:387],
	28160: _Status_name[387:414],
	28416: _Status_name[414:432],
	36864: _Status_name[432:460],
}

func (i Status) String() string {
	if str, ok := _Status_map[i]; ok {
		return str
	}
	return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
}
