// Code generated by "stringer -type=Status,StatusCategory"; DO NOT EDIT.

package apdu

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusNoFurtherQualification-36864]
	_ = x[StatusWarningNonVolatileMemoryUnchangedNoInformation-25090]
	_ = x[StatusWarningNonVolatileMemoryUnchangePartOfReturnedDataCorrupted-25217]
	_ = x[StatusWarningNonVolatileMemoryUnchangeEndOfFileOrRecordReachedPrematurely-25218]
	_ = x[StatusWarningNonVolatileMemoryUnchangeSelectedFileDeactivated-25219]
	_ = x[StatusWarningNonVolatileMemoryUnchangeFileControlInvalid-25220]
	_ = x[StatusWarningNonVolatileMemoryUnchangeFileTerminated-25221]
	_ = x[StatusWarningNonVolatileMemoryUnchangeNoInputDataFromSensor-25222]
	_ = x[StatusWarningNonVolatileMemoryChangedNoInformation-25344]
	_ = x[StatusWarningNonVolatileMemoryChangedFileFull-25473]
	_ = x[StatusErrorWrongLength-26368]
	_ = x[StatusErrorWrongParameters-27392]
	_ = x[StatusErrorUnsupportedInstructionCode-27904]
	_ = x[StatusErrorUnsupportedClass-28160]
	_ = x[StatusErrorUnknown-28416]
}

const (
	_Status_name_0 = "StatusWarningNonVolatileMemoryUnchangedNoInformation"
	_Status_name_1 = "StatusWarningNonVolatileMemoryUnchangePartOfReturnedDataCorruptedStatusWarningNonVolatileMemoryUnchangeEndOfFileOrRecordReachedPrematurelyStatusWarningNonVolatileMemoryUnchangeSelectedFileDeactivatedStatusWarningNonVolatileMemoryUnchangeFileControlInvalidStatusWarningNonVolatileMemoryUnchangeFileTerminatedStatusWarningNonVolatileMemoryUnchangeNoInputDataFromSensor"
	_Status_name_2 = "StatusWarningNonVolatileMemoryChangedNoInformation"
	_Status_name_3 = "StatusWarningNonVolatileMemoryChangedFileFull"
	_Status_name_4 = "StatusErrorWrongLength"
	_Status_name_5 = "StatusErrorWrongParameters"
	_Status_name_6 = "StatusErrorUnsupportedInstructionCode"
	_Status_name_7 = "StatusErrorUnsupportedClass"
	_Status_name_8 = "StatusErrorUnknown"
	_Status_name_9 = "StatusNoFurtherQualification"
)

var (
	_Status_index_1 = [...]uint16{0, 65, 138, 199, 255, 307, 366}
)

func (i Status) String() string {
	switch {
	case i == 25090:
		return _Status_name_0
	case 25217 <= i && i <= 25222:
		i -= 25217
		return _Status_name_1[_Status_index_1[i]:_Status_index_1[i+1]]
	case i == 25344:
		return _Status_name_2
	case i == 25473:
		return _Status_name_3
	case i == 26368:
		return _Status_name_4
	case i == 27392:
		return _Status_name_5
	case i == 27904:
		return _Status_name_6
	case i == 28160:
		return _Status_name_7
	case i == 28416:
		return _Status_name_8
	case i == 36864:
		return _Status_name_9
	default:
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusBytesAvailable-97]
	_ = x[StatusWarningNonVolatileMemoryUnchanged-98]
	_ = x[StatusWarningNonVolatileMemoryChanged-99]
	_ = x[StatusErrorNonVolatileMemoryUnchanged-100]
	_ = x[StatusErrorNonVolatileMemoryChanged-101]
	_ = x[StatusErrorSecurityIssue-102]
	_ = x[StatusErrorFunctionUnsupported-104]
	_ = x[StatusErrorCommandNotAllowed-105]
	_ = x[StatusErrorWrongParametersWithInfo-106]
	_ = x[StatusErrorWrongLe-108]
}

const (
	_StatusCategory_name_0 = "StatusBytesAvailableStatusWarningNonVolatileMemoryUnchangedStatusWarningNonVolatileMemoryChangedStatusErrorNonVolatileMemoryUnchangedStatusErrorNonVolatileMemoryChangedStatusErrorSecurityIssue"
	_StatusCategory_name_1 = "StatusErrorFunctionUnsupportedStatusErrorCommandNotAllowedStatusErrorWrongParametersWithInfo"
	_StatusCategory_name_2 = "StatusErrorWrongLe"
)

var (
	_StatusCategory_index_0 = [...]uint8{0, 20, 59, 96, 133, 168, 192}
	_StatusCategory_index_1 = [...]uint8{0, 30, 58, 92}
)

func (i StatusCategory) String() string {
	switch {
	case 97 <= i && i <= 102:
		i -= 97
		return _StatusCategory_name_0[_StatusCategory_index_0[i]:_StatusCategory_index_0[i+1]]
	case 104 <= i && i <= 106:
		i -= 104
		return _StatusCategory_name_1[_StatusCategory_index_1[i]:_StatusCategory_index_1[i+1]]
	case i == 108:
		return _StatusCategory_name_2
	default:
		return "StatusCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
